import React from 'react'
import term from '../assets/images/termsAndConditions.png'
export default function Termsandcondition() {
    return (
        <div className="termandCondition">
            <div className='terms'>
                <div className="back">
                    <img src={term} alt="" />
                </div>

            </div>
            <div className="container">
                <div className="termHeading">Terms & Condtions</div>
                <div className="small">As updated on DEC 28, 2023</div>

                <div className="para1">
                    <div className="para-heading">GENERAL</div>
                    <div className="para">Welcome to our website. If you continue to browse and use this website you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern Leverage EdTech Private Limited’s relationship with you in relation to this website/mobile and the product which you purchase through this website/mobile . The term ‘Leverage EdTech Private Limited’ or ‘us’ or ‘we’ refers to the owner of the website/mobile . The term ‘you’ refers to the user/viewer of our website.</div>
                    <br />
                    <div className="para">This Agreement is an electronic record in terms of Information Technology Act, 2000, and generated by a computer system and does not require any physical or digital signatures.</div>
                </div>
                <div className="para1">
                    <div className="para-heading">Way 2 Admission FEE</div>
                    <div className="para">Way 2 Admission has arrangement (directly/indirectly) with the universities. Way 2 Admission earns after successful enrolment of a student in a University, as per their norms.</div>
                </div>
                <div className="para1">
                    <div className="para-heading">ABOUT US</div>
                    <div className="para">The use of this platform and the products purchased on this platform is subject to the following terms of use:</div>
                    <br />
                    <div className="para">
                        The content of the pages of this platform is for your general information and use only. It is subject to change without notice.
                    </div>
                    <br />
                    <div className="para">
                        Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this platform for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                    </div>
                    <br />
                    <div className="para">
                        Your use of any information or materials on this platform is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products or information available through this platform meet your specific requirements.
                    </div>
                    <br />
                    <div className="para">
                        Your use of our products and services provided for herein is solely for your personal and non-commercial use. Any use other than for personal purposes is prohibited. Your personal and non-commercial use of our services shall be subjected to the following restrictions: i) You may not decompile, reverse engineer, or disassemble the contents of our products, or (c) remove any copyright, trademark registration, or other proprietary notices from the contents of our products. ii) You will not (a) use our product or service for commercial purposes of any kind, or (b) advertise or sell any products, services or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use our products and services in any way that is unlawful, or harms Leverage EdTech Private Limited or any other person or entity as determined by Leverage EdTech Private Limited.
                    </div>
                    <br />
                    <div className="para">
                        Leverage EdTech Private Limited products and / or services, including the Leverage EdTech Private Limited application and content, may not be compatible to all devices. Leverage EdTech Private Limited shall not be obligated to provide workable products and / or services for any phones/tablets unless stated otherwise.
                    </div>
                    <div className="para">
                        Leverage EdTech Private Limited or any of its subsidiaries or content partners shall have no responsibility for any loss or damage caused to tablet or phone or any other hardware and / or software, including loss of data or effect on the processing speed of the tablet, those results from the use of our products and services.
                    </div>
                </div>


                <div className="para1">
                    <div className="para-heading">TERM & TERMINATION</div>
                    <div className="para">
                        This Agreement will remain in full force and effect until terminated, for using the platform or purchasing the products in any form or capacity. Provided, we have the right to immediately terminate your access or usage and remove non-compliant information or material, in case of non-compliance with the terms and conditions or our privacy policy.
                    </div>
                    <br />
                    <div className="para">
                        The User shall be obligated to clear any dues with us for any of its Services which you have procured. Leverage EdTech Private Limited shall not be liable to you or any third party for any termination of your access to the Services.
                    </div>
                </div>

                <div className="para1">
                    <div className="para-heading">GOVERNING LAW</div>
                    <div className="para">
                        The jurisdictional court of New Delhi, India shall have sole jurisdiction over any claim arising from, or related to, a visit to / use of the platform or purchase of the products. In case you are from a different country, we retain the right to bring proceedings against you for breach of any of the terms and conditions in your country of residence, country of use or other relevant country. The laws of New Delhi, India govern this Agreement and these terms and conditions of use of the platform or purchase of the products.
                    </div>

                    <br />
                    <div className="para">
                        Leverage EdTech Private Limited accepts no liability whatsoever, direct or indirect, for non-compliance with the laws of any country other than that of India, and the mere fact that the platform can be accessed or used in a country other than India will not imply that we accede to the laws of such country.
                    </div>
                </div>


                <div className="para1">
                    <div className="para-heading">UniConnect's Terms & Conditions</div>
                    <div className="para">
                        The student agrees to authorise Way 2 Admission as his/her agent and help with his/her applications & other admission related services.
                    </div>
                    <br />
                    <div className="para">
                        The student agrees to change his/her agent to Way 2 Admission in case there is another agent already authorised prior to this.
                    </div>
                </div>

                <div className="para1">
                    <div className="para-heading">
                        Our Scholarship Terms & Conditions
                    </div>
                    <div className="para">
                        The reward will be processed once you pay the deposit at the university and receive your Visa
                    </div>

                    <div className="para">
                        The scholarship amount is to be determined on the basis of your application and overall profile
                    </div>
                    <div className="para">
                        Selection for the scholarship to be solely at the discretion of the Way 2 Admission jury and corresponding guidelines
                    </div>
                </div>

                <div className="para1">
                    <div className="para-heading">
                        Payments
                    </div>
                    <div className="para" >
                        Leverage does not require you to make payments for any purposes in any individual’s bank accounts. Any payments for any purpose including purposes of applications, deposit, tuition fee payments or to purchase any service packages offered by Leverage must be made through the official Leverage payment channels or specific university payment accounts, as the case maybe.
                    </div>
                </div>
            </div>
        </div>
    )
}
